#17 Create Board CRUD API
WinterSpringProject/PROJECT-GLFP pull request #28
Opened 2021-02-13 15:13 UTC by bluewink

Create Board CRUD API 구현 & gitignore 적용

2021-02-14 03:03 UTC, gyumnnii requested changes

2021-02-14 03:03 UTC, gyumnnii commented on src/main/java/glfp/glfp/controller/BoardController.java
> +    public BoardController(BoardService boardService) { this.boardService = boardService; }
짧은 함수 혹은 메서드더라도
한 줄에 모두 다 작성하는 것은
가독성 측면에서 좋지 않습니다.

public BoardController(parameter){
  ...
}

의 형식을 지켜주시면 좋을 것 같습니다.

2021-02-14 03:03 UTC, gyumnnii commented on src/main/java/glfp/glfp/domain/entity/Board.java
>          this.matchStatus = matchStatus;
matchStatus라는 변수명으로는 어떤 역할인지
감이 안잡히는데 어떤 변수인지 여쭤봐도 될까요?

2021-02-14 03:03 UTC, gyumnnii commented on src/main/java/glfp/glfp/service/BoardService.java
> +        for(Board board : boardList){       // 함수화하여 최적화할 수 있음
이후에 함수로 따로 모듈화를 할 예정이라면
TODO 등의 키워드를 이용해 다른 팀원들도 알아보기 쉬운 주석을 작성해주세요

간단하게 구현할 수 있는 것이라면 주석을 따로 작성하는 것 보단 구현을 한 후에 PR을 날려주세요~

2021-02-14 03:03 UTC, gyumnnii commented on src/main/java/glfp/glfp/service/BoardService.java
> +    public void revise(BoardDto boardDto){
위에 정의한 메소드와 같이
reviseBoard와 같은 메서드 명을 사용하면 좋을 것 같습니다

2021-02-14 03:03 UTC, gyumnnii commented on src/main/java/glfp/glfp/service/BoardService.java
> +    public void delete(Long id){
revise와 동일하게 메서드명 통일해주세요

2021-02-14 03:03 UTC, gyumnnii commented on src/main/resources/application.properties
> +spring.datasource.username=sb
DB 관련 정보인 것 같은데 레포지토리에 올라오지 않게 숨겨둘 순 없을까요? 보안상 좋지 않을 것 같습니당

2021-02-14 09:17 UTC, Ohhong commented on src/main/resources/application.properties
> +spring.datasource.username=sb
해당 내용에 추가적으로 저는 vault 라는 것을 통해서 관리 하는데요
vault를 적용하시려면 시간이 걸릴 수 있으니 (나중에라도 한번 봐보시는 걸 추천드립니다)
.env 파일을 사용하는 법에 대해서 찾아보시고
README에 .env에 어떤 내용이 들어가면 좋을지에 대한 부분(개발 환경)을 명시해주면 좋습니다.

2021-02-14 09:50 UTC, simsulison commented on src/main/java/glfp/glfp/domain/entity/Board.java
>          this.matchStatus = matchStatus;
게시물을 통해 아직 매칭 대기 중인지, 매칭 진행 중인지,  매칭이 완료되었는지를 보이기 위한 변수로 사용될 예정입니다.

2021-02-14 10:39 UTC, gyumnnii commented on src/main/java/glfp/glfp/domain/entity/Board.java
>          this.matchStatus = matchStatus;
감사합니다 이해됐습니당~

2021-02-17 03:20 UTC, gyumnnii approved these changes
수정하신걸 너무 늦게 확인했네요 죄송합니다
고생 많으셨습니다~

그리고 approve 받아야 할 인원이 많아보이는데 한 2명정도로 줄이는 건 어떠신가요?

2021-02-17 03:32 UTC, Ohhong approved these changes

2021-02-17 03:39 UTC, simsulison approved these changes

2021-02-17 03:40 UTC, merged