#29 #30 Create spring security, chat prototype
WinterSpringProject/PROJECT-GLFP pull request #31
Opened 2021-02-21 01:56 UTC by bluewink

spring security, chat prototype을 구현했습니다.

2021-02-21 18:09 UTC, gyumnnii requested changes

2021-02-21 18:09 UTC, gyumnnii commented on src/main/java/glfp/glfp/config/SecurityConfig.java
> +        http
메소드 호출이 계속해서 체이닝 되는 코드들을 일명 "기차 충돌" 문제라고 합니다.
이는 클린 코드 작성에서 많이 언급되는 문제 중에 하나인데
이러한 경우는 가독성에 문제가 생기기 때문에 지양해야 하는 코드 작성 방식입니다.

해당 문제를 주석을 통해서 해결하려고 한 모습이 엿보이긴 하지만
주석이라는 것은 정말 필요한 때가 아니면 작성하지 않는 편이 좋기에
"디미터 법칙"을 적용하여 의미있는 변수명을 이용해서 메소드 체이닝을 해결하는 방식을 추천드립니다.

- 디미터 법칙 예시
```ts
// Bad
let result=a.method1().method2().method3()

// Good
let somethingMeaningful1=a.method1()
let somethingMeaningful2=somethingMeaningful1.method2()
let somethingMeaningful3=somethingMeaningful2.method3()
```

참조 : 디미터 법칙 (https://coding-start.tistory.com/m/264)

2021-02-21 18:09 UTC, gyumnnii commented on src/main/java/glfp/glfp/controller/MessageController.java
> +        System.out.println("handling send msg: " + message + "to : "+ to);
로깅을 위해 남겨둔 코드라면 괜찮지만
개발 중에 디버깅을 위한 코드였다면 삭제하는 것이 낫겠네요.

2021-02-21 18:09 UTC, gyumnnii commented on src/main/java/glfp/glfp/controller/MessageController.java
> +        if (result != null) {
의미 없는 주석이라는 생각이 듭니다.
차라리 주석 대신에 변수명을 좀 더 의미있게 작성하는 편은 어떨까요?

2021-02-21 18:09 UTC, gyumnnii commented on src/main/java/glfp/glfp/security/handler/LoginSuccessHandler.java
> +        //로그인 성공시 처리할 로직을 구현.
코드의 내용을 다시 한번 언급해 주는 식의 주석은 필요 없을 것 같아 보입니다.

자신이 작성한 코드를 남에게 이해시켜 주기 위함이였다면
시나리오를 코드 작성 이전에 협의 및 공유 하셔서
불필요한 주석은 제거하는 것이 좋겠네요.

2021-02-21 18:09 UTC, gyumnnii commented on src/main/java/glfp/glfp/controller/MainController.java
> +@Controller     //TODO: 추후 restController로 수정
TODO를 활용한 주석을 잘 작성해주셨네요!

이미 사용하고 있으신진 모르겠지만 VSCode extension인 TODO Highlighting 을 이용하는 것도 추천드립니다.

2021-02-21 18:09 UTC, gyumnnii commented on src/main/java/glfp/glfp/service/MemberService.java
> +        Optional<Member> result = memberRepository.findById(mId);
다른 코드들에서도 result라는 변수명이 흔히 쓰이는 것 같은데
좀 더 의미있는 변수명을 사용해주셨으면 합니다.

2021-02-27 12:02 UTC, bluewink commented on src/main/java/glfp/glfp/controller/MessageController.java
> +        System.out.println("handling send msg: " + message + "to : "+ to);
로깅을 위한 코드라 남겨두었다가 추후 log4j로 교체하겠습니다!

2021-02-27 12:03 UTC, bluewink commented on src/main/java/glfp/glfp/controller/MainController.java
> +@Controller     //TODO: 추후 restController로 수정
넵! intelij 사용 중인데 default로 highlighting 해주더라고요! 감사합니다

2021-02-27 12:03 UTC, bluewink commented on src/main/java/glfp/glfp/service/MemberService.java
> +        Optional<Member> result = memberRepository.findById(mId);
넵 의미있는 변수명으로 수정하겠습니다!

2021-02-27 12:18 UTC, bluewink commented on src/main/java/glfp/glfp/config/SecurityConfig.java
> +        http
디미터 법칙을 처음 알게되었네요!!
스프링 시큐리티를 처음 적용하다보니 공부할겸 주석을 달아놓았습니다! 추후 삭제하겠습니다.
다만, 위 코드가 스프링 시큐리티를 처음으로 환경설정하는 코드인데, 구글링 해보니 백이면 백 저렇게 체이닝 코드로 작성했더라고요. 이유가 무엇인지 조금더 찾아보고 생각해보겠습니다.

2021-02-28 02:37 UTC, gyumnnii commented on src/main/java/glfp/glfp/config/SecurityConfig.java
> +        http
제가 저 프레임워크들을 잘 몰라서 코드 관련 리뷰는 해드리지만 해당 의견이 맞는 말은 아닐 수 있어서 선택적으로 받아들여 주세요!

2021-02-28 02:37 UTC, simsulison approved these changes

2021-02-28 05:54 UTC, gyumnnii approved these changes
💪 LGTM 💪

2021-02-28 05:54 UTC, gyumnnii approved these changes

2021-02-28 12:39 UTC, k0k0k02 approved these changes

2021-02-28 12:40 UTC, merged